import { useEffect, useState } from "react";
import type { EvidenceResult } from "./EvidenceUpload";

export function SatelliteImpact({ evidence }: { evidence: EvidenceResult | null }) {
  const [afterVisible, setAfterVisible] = useState(50);
  const [assetError, setAssetError] = useState(false);
  const impact = evidence?.impact_assessment;
  useEffect(() => { setAfterVisible(50); }, [evidence]);
  return <section className="satellite-section" aria-labelledby="satellite-title"><div className="evidence-heading"><div><p className="eyebrow">PREPARED PILOT ANALYSIS</p><h2 id="satellite-title">Satellite Before / After Impact</h2><p>Illustrative Demo Watershed · 38.6 ha · offline prepared assets</p></div><span className="demo-chip">DEMO DATA</span></div>{assetError ? <div className="feature-error">Prepared satellite assets are unavailable. Restore the local <code>data/satellite</code> folder and reload.</div> : <><div className="satellite-compare"><img src="/satellite/pilot-before.png" onError={() => setAssetError(true)} alt="Illustrative pilot watershed before intervention" /><div className="after-layer" style={{ clipPath: `inset(0 0 0 ${afterVisible}%)` }}><img src="/satellite/pilot-after.png" onError={() => setAssetError(true)} alt="Illustrative pilot watershed after intervention" /></div><span className="compare-label before">Before · 15 Feb 2024</span><span className="compare-label after">After · 18 Feb 2025</span><input aria-label="Reveal after image" type="range" min="0" max="100" value={afterVisible} onChange={(event) => setAfterVisible(Number(event.target.value))} /></div><div className="satellite-details"><p><strong>Source:</strong> JalDrishti prepared illustrative pilot assets</p><p><strong>NDVI:</strong> 0.31 → 0.49 <span>+0.18</span></p><p><strong>NDWI:</strong> 0.12 → 0.21 <span>+0.09</span></p></div><div className="impact-factor"><strong>Indicator history · pilot confidence</strong><span>15 Feb 2024: NDVI 0.31 / NDWI 0.12 → 18 Feb 2025: NDVI 0.49 / NDWI 0.21</span><small>Observed/prepared indicators only; no causal conclusion is made.</small></div>{impact ? <article className="impact-card"><div><p className="eyebrow">WATERSHED INTERVENTION IMPACT INDEX</p><strong>{impact.score}<small>/100</small></strong><span>{impact.classification}</span></div><div><p>{impact.interpretation}</p>{impact.factors.map((factor) => <div className="impact-factor" key={factor.name}><strong>{factor.name} · {Math.round(factor.weight * 100)}%</strong><span>{factor.value}/100 · contributes {factor.contribution}</span><small>{factor.explanation}</small></div>)}</div></article> : <p className="satellite-await">No evidence loaded yet. Upload a field image or choose Load Demo Scenario to calculate the pilot Impact Score.</p>}</>}<p className="limitation-note">Limitation: satellite-index changes can also be influenced by season, rainfall, cloud cover, and crop cycles. This pilot comparison does not establish causality.</p></section>;
}
